### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Akimotorakiyu** [gzstokiyama/vue-pop-colorpicker#3]
typescript support

**Comment by Akimotorakiyu** [comment]
![image](https://user-images.githubusercontent.com/31165554/72892972-d2b65a00-3d52-11ea-8310-582e2c6ccb8d.png)

**Comment by gzstokiyama** [comment]
sorry this is only the bug fix version of the original repo,new features will NOT add. you can fork this repo to start a new dev branch
